version: 2.1

workflows:
  ci-pipeline-pr:
    jobs:
      - tests:
          filters:
            branches:
              ignore: /master/
      - test-dists-ubuntu:
          filters:
            branches:
              ignore: /master/
          requires:
            - tests
  ci-pipeline-master:
    jobs:
      - tests:
          filters:
            branches:
              only: /master/
      - test-dists-ubuntu:
          filters:
            branches:
              only: /master/
          requires:
            - tests
      - approve-deploy-github:
          filters:
            branches:
              only: /master/
          type: approval
          requires:
            - test-dists-ubuntu
      - deploy-github:
          filters:
            branches:
              only: /master/
          requires:
            - approve-deploy-github
      - approve-deploy-all:
          filters:
            branches:
              only: /master/
          type: approval
          requires:
            - deploy-github
      - deploy-all:
          filters:
            branches:
              only: /master/
          requires:
            - approve-deploy-all

jobs:
  tests:
    machine: true
    steps:
      - checkout
      - bazel_install
      - bazel_add_rbe_credential
      - bazel:
          command: bazel test //migrator:migrator-test --test_output=streamed
  test-dists:
    machine: true
    steps:
      - checkout
      - bazel_install
      - bazel_add_rbe_credential
      - bazel:
          command: bazel build //...
  test-dists-ubuntu:
    machine: true
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y software-properties-common
      - run: sudo add-apt-repository ppa:openjdk-r/ppa -y
      - run: sudo apt-get update
      - run: sudo apt-get install -y sudo gcc build-essential openjdk-8-jdk python-dev unzip curl git

      - checkout
      - bazel_install
      - bazel_add_rbe_credential
      - bazel:
          command: bazel --host_jvm_args=-Xmx16g build //...

  deploy-github:
    machine: true
    steps:
      - checkout
      - bazel_install
      - bazel_add_rbe_credential
      - run: echo test succeeded.
  deploy-all:
    machine: true
    steps:
      - checkout
      - bazel_install
      - bazel_add_rbe_credential
      - run: echo test succeeded.

commands:
  bazel_install:
    steps:
      - run:
          name: Bazel - Install
          command: |
            curl -OL https://github.com/bazelbuild/bazel/releases/download/0.20.0/bazel-0.20.0-installer-linux-x86_64.sh
            chmod +x bazel-0.20.0-installer-linux-x86_64.sh
            sudo ./bazel-0.20.0-installer-linux-x86_64.sh
  bazel_add_rbe_credential:
    steps:
      - run:
          name: Bazel - Add RBE Credential
          command: |
            if [[ -n "$BAZEL_RBE_CREDENTIAL" ]]; then
              BAZEL_RBE_CREDENTIAL_LOCATION=~/.config/gcloud/application_default_credentials.json
              echo "An RBE credential is found and will be saved to $BAZEL_RBE_CREDENTIAL_LOCATION. Bazel will be executed with RBE support."
              mkdir -p ~/.config/gcloud/
              echo $BAZEL_RBE_CREDENTIAL > "$BAZEL_RBE_CREDENTIAL_LOCATION"
            else
              echo "No RBE credential found. Bazel will be executed locally without RBE support."
            fi

  bazel:
    parameters:
      command:
          type: string
    steps:
      - run:
          name: Bazel - Execute
          command: |
            if [[ -f ~/.config/gcloud/application_default_credentials.json ]]; then
              echo "Bazel will be executed with RBE support. This means the build is remotely executed and the cache will be re-used by subsequent CI jobs."
              CMD="<< parameters.command >> --config=rbe"
            else
              echo "Bazel will be executed locally (without RBE support)."
              CMD="<< parameters.command >>"
            fi
            echo "Executing $CMD"
            $CMD
